version: '3'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_PWD=Oracle123#
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_SYS_PASSWORD=Oracle123#
      - ORACLE_PDB_PASSWORD=Oracle123#
      - ORACLE_EDITION=express
    ports:
      - "1521:1521"
      - "5500:5500"
    container_name: oracle-xe
